# Import & Clean

In [4]:
import pandas as pd
import pycountry

import warnings

# Ignore all warnings
warnings.filterwarnings('ignore')

temperature = pd.read_csv('Data Assets/country_temperatures.csv', encoding="ISO-8859-1")
emissions = pd.read_csv('Data Assets/country_emissions.csv', encoding="ISO-8859-1")
disasters = pd.read_csv('Data Assets/country_disasters.csv', encoding="ISO-8859-1")
gobal_energy = pd.read_csv('Data Assets/Annual Global energy consumption.csv', encoding="ISO-8859-1")
global_temps = pd.read_csv('Data Assets/Annual Global temperature change.csv', encoding="ISO-8859-1")

## Cleaning 'temperature'

In [4]:
temperature = temperature[temperature['Element'] != 'Standard Deviation']

# List of months you want to exclude
months_to_exclude = ['Dec\x96Jan\x96Feb', 'Mar\x96Apr\x96May', 'Jun\x96Jul\x96Aug', 'Sep\x96Oct\x96Nov', 'Meteorological year']

# Filter the DataFrame to exclude those values in the 'Months' column
temperature = temperature[~temperature['Months'].isin(months_to_exclude)]

temperature.drop(columns= ['Area Code', 'Months Code', 'Element Code', 'Unit', 'Element'], inplace = True)

temperature.drop(columns=temperature.filter(regex='^Y(196[1-9]|19[7-8][0-9])$').columns, inplace=True)

# Strip 'Y' from column names that start with 'Y'
temperature.rename(columns=lambda x: x[1:] if x.startswith('Y') else x, inplace=True)

temperature.dropna(how = 'any', inplace = True)

# List of non-country entries
non_country_entries = [
    'World', 'Africa', 'Eastern Africa', 'Middle Africa', 'Northern Africa', 'Southern Africa', 'Western Africa',
    'Americas', 'Northern America', 'Central America', 'Caribbean', 'South America', 'Asia', 'Central Asia',
    'Eastern Asia', 'Southern Asia', 'South-Eastern Asia', 'Western Asia', 'Europe', 'Eastern Europe', 
    'Northern Europe', 'Southern Europe', 'Western Europe', 'Oceania', 'Australia and New Zealand', 'Melanesia', 
    'Micronesia', 'Polynesia', 'European Union', 'Least Developed Countries', 'Land Locked Developing Countries', 
    'Small Island Developing States', 'Low Income Food Deficit Countries', 'Net Food Importing Developing Countries', 
    'Annex I countries', 'Non-Annex I countries', 'OECD'
]

# Mapping function to filter out non-country rows
def filter_countries(df, column_name):
    # Filter the dataframe to keep only rows where the value is not in non_country_entries
    df = df[~df[column_name].isin(non_country_entries)]
    return df

# Apply the function to the DataFrame
temperature = filter_countries(temperature, 'Area')

temperature.rename(columns={'Area': 'Country'}, inplace=True)

temperature_country_mapping = {
    'Afghanistan': 'Afghanistan',
    'Albania': 'Albania',
    'Algeria': 'Algeria',
    'Andorra': 'Andorra',
    'Angola': 'Angola',
    'Anguilla': 'Anguilla',
    'Antarctica': 'Antarctica',
    'Argentina': 'Argentina',
    'Australia': 'Australia',
    'Austria': 'Austria',
    'Bahamas': 'Bahamas',
    'Bahrain': 'Bahrain',
    'Bangladesh': 'Bangladesh',
    'Barbados': 'Barbados',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Bhutan': 'Bhutan',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Botswana': 'Botswana',
    'Brazil': 'Brazil',
    'British Virgin Islands': 'British Virgin Islands',
    'Brunei Darussalam': 'Brunei',
    'Bulgaria': 'Bulgaria',
    'Burkina Faso': 'Burkina Faso',
    'Cabo Verde': 'Cabo Verde',
    'Cambodia': 'Cambodia',
    'Cameroon': 'Cameroon',
    'Canada': 'Canada',
    'Central African Republic': 'Central African Republic',
    'Chad': 'Chad',
    'Channel Islands': 'Channel Islands',
    'Chile': 'Chile',
    'China': 'China',
    'China, Hong Kong SAR': 'Hong Kong',
    'China, Macao SAR': 'Macao',
    'China, mainland': 'China',
    'China, Taiwan Province of': 'Taiwan',
    'Cocos (Keeling) Islands': 'Cocos Islands',
    'Colombia': 'Colombia',
    'Comoros': 'Comoros',
    'Congo': 'Congo',
    'Costa Rica': 'Costa Rica',
    "Côte d'Ivoire": "Ivory Coast",
    'Cuba': 'Cuba',
    'Cyprus': 'Cyprus',
    "Democratic People's Republic of Korea": 'North Korea',
    'Democratic Republic of the Congo': 'Democratic Republic of the Congo',
    'Denmark': 'Denmark',
    'Dominica': 'Dominica',
    'Dominican Republic': 'Dominican Republic',
    'Ecuador': 'Ecuador',
    'Egypt': 'Egypt',
    'El Salvador': 'El Salvador',
    'Equatorial Guinea': 'Equatorial Guinea',
    'Eswatini': 'Eswatini',
    'Faroe Islands': 'Faroe Islands',
    'Fiji': 'Fiji',
    'Finland': 'Finland',
    'France': 'France',
    'French Guiana': 'French Guiana',
    'French Polynesia': 'French Polynesia',
    'French Southern and Antarctic Territories': 'French Southern and Antarctic Territories',
    'Gabon': 'Gabon',
    'Gambia': 'Gambia',
    'Germany': 'Germany',
    'Ghana': 'Ghana',
    'Gibraltar': 'Gibraltar',
    'Greece': 'Greece',
    'Greenland': 'Greenland',
    'Grenada': 'Grenada',
    'Guadeloupe': 'Guadeloupe',
    'Guatemala': 'Guatemala',
    'Guinea': 'Guinea',
    'Guinea-Bissau': 'Guinea-Bissau',
    'Guyana': 'Guyana',
    'Haiti': 'Haiti',
    'Holy See': 'Vatican City',
    'Honduras': 'Honduras',
    'Hungary': 'Hungary',
    'Iceland': 'Iceland',
    'India': 'India',
    'Indonesia': 'Indonesia',
    'Iran (Islamic Republic of)': 'Iran',
    'Iraq': 'Iraq',
    'Ireland': 'Ireland',
    'Isle of Man': 'Isle of Man',
    'Israel': 'Israel',
    'Italy': 'Italy',
    'Jamaica': 'Jamaica',
    'Japan': 'Japan',
    'Jordan': 'Jordan',
    'Kenya': 'Kenya',
    'Kuwait': 'Kuwait',
    "Lao People's Democratic Republic": 'Laos',
    'Lebanon': 'Lebanon',
    'Lesotho': 'Lesotho',
    'Liberia': 'Liberia',
    'Libya': 'Libya',
    'Liechtenstein': 'Liechtenstein',
    'Madagascar': 'Madagascar',
    'Malawi': 'Malawi',
    'Malaysia': 'Malaysia',
    'Maldives': 'Maldives',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Martinique': 'Martinique',
    'Mauritania': 'Mauritania',
    'Mauritius': 'Mauritius',
    'Mayotte': 'Mayotte',
    'Mexico': 'Mexico',
    'Monaco': 'Monaco',
    'Mongolia': 'Mongolia',
    'Morocco': 'Morocco',
    'Mozambique': 'Mozambique',
    'Myanmar': 'Myanmar',
    'Namibia': 'Namibia',
    'Nepal': 'Nepal',
    'Netherlands': 'Netherlands',
    'Netherlands Antilles (former)': 'Netherlands',
    'New Caledonia': 'New Caledonia',
    'New Zealand': 'New Zealand',
    'Nicaragua': 'Nicaragua',
    'Niger': 'Niger',
    'Nigeria': 'Nigeria',
    'Norway': 'Norway',
    'Oman': 'Oman',
    'Pakistan': 'Pakistan',
    'Palestine': 'Palestine',
    'Panama': 'Panama',
    'Papua New Guinea': 'Papua New Guinea',
    'Paraguay': 'Paraguay',
    'Peru': 'Peru',
    'Philippines': 'Philippines',
    'Poland': 'Poland',
    'Portugal': 'Portugal',
    'Puerto Rico': 'Puerto Rico',
    'Qatar': 'Qatar',
    'Republic of Korea': 'South Korea',
    'Réunion': 'Réunion',
    'Romania': 'Romania',
    'Saint Helena, Ascension and Tristan da Cunha': 'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Lucia': 'Saint Lucia',
    'Saint Pierre and Miquelon': 'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'San Marino': 'San Marino',
    'Saudi Arabia': 'Saudi Arabia',
    'Senegal': 'Senegal',
    'Seychelles': 'Seychelles',
    'Sierra Leone': 'Sierra Leone',
    'Somalia': 'Somalia',
    'South Africa': 'South Africa',
    'Spain': 'Spain',
    'Sri Lanka': 'Sri Lanka',
    'Suriname': 'Suriname',
    'Svalbard and Jan Mayen Islands': 'Svalbard and Jan Mayen',
    'Sweden': 'Sweden',
    'Switzerland': 'Switzerland',
    'Syrian Arab Republic': 'Syria',
    'Thailand': 'Thailand',
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Tunisia': 'Tunisia',
    'Turkey': 'Turkey',
    'Tuvalu': 'Tuvalu',
    'Uganda': 'Uganda',
    'United Arab Emirates': 'United Arab Emirates',
    'United Kingdom': 'United Kingdom',
    'United Republic of Tanzania': 'Tanzania',
    'United States of America': 'United States',
    'United States Virgin Islands': 'US Virgin Islands',
    'Uruguay': 'Uruguay',
    'Vanuatu': 'Vanuatu',
    'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'Wake Island': 'Wake Island',
    'Wallis and Futuna Islands': 'Wallis and Futuna',
    'Western Sahara': 'Western Sahara',
    'Zambia': 'Zambia',
    'Zimbabwe': 'Zimbabwe'
}

# Apply the country name standardization mapping to the temperature DataFrame
temperature['Country'] = temperature['Country'].replace(temperature_country_mapping)

temperature.rename(columns={'Area': 'Country'}, inplace=True)

temperature.reset_index(drop=True, inplace=True)

## Cleaning 'emissions'

In [11]:
emissions.drop(columns='Region', inplace =True)

emissions_country_mapping = {
   'USA': 'United States',
    'UK': 'United Kingdom',
    'Czech Republic': 'Czechia',
    'Iran (Islamic Republic Of)': 'Iran',
    'Russian Federation': 'Russia',
    'Venezuela (Bolivarian Republic Of)': 'Venezuela',
    'Yemen (Republic Of)': 'Yemen',
    'Bosnia And Herzegovina': 'Bosnia',
    'South Korea': 'Republic Of Korea',
    'North Korea': 'Democratic People\'s Republic Of Korea',
    'Macedonia (Former Yugoslav Republic Of)': 'North Macedonia',
    'Eswatini': 'Swaziland',  # Note: "Eswatini" is the new name, you may want to standardize on one
    'Syria (Syrian Arab Republic)': 'Syria',
    'Laos (Lao People\'s Democratic Republic)': 'Laos',
    'Palestinian Territory, Occupied': 'Palestine',
    'Ivory Coast': 'Côte d\'Ivoire',
    'Brunei Darussalam': 'Brunei',
    'Timor-Leste': 'East Timor',
    'Hong Kong (China)': 'Hong Kong',
    'Macau (China)': 'Macau',
    'United Arab Emirates': 'UAE',
    'Democratic Republic Of Congo': 'Democratic Republic of the Congo',
    'Republic Of Congo': 'Republic of the Congo',
    'Swaziland': 'Eswatini',
    'Korea, North': 'North Korea',
    'Korea, South': 'South Korea',
    'Bahamas, The': 'Bahamas',
    'Viet Nam': 'Vietnam',
    'Czech Republic (Czechia)': 'Czechia',
    'Côte d\'Ivoire': 'Ivory Coast',
    'Saint Kitts and Nevis': 'St. Kitts and Nevis',
    'Saint Lucia': 'St. Lucia',
    'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
    'Antigua And Barbuda': 'Antigua and Barbuda',
    'Brunei Darussalam': 'Brunei',
    'The Gambia': 'Gambia',
    'Micronesia (Federated States Of)': 'Micronesia',
    'Sao Tome And Principe': 'São Tomé and Príncipe',
    'United Republic Of Tanzania': 'Tanzania',
    'Congo, The Democratic Republic Of The': 'Democratic Republic of the Congo',
    'United States of America': 'United States',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'Republic of Korea': 'South Korea',
    'People\'s Republic of China': 'China',
    'Myanmar (Burma)': 'Myanmar',
    'Republic of the Congo': 'Congo',
    'Central African Republic': 'Central African Republic',
    'Equatorial Guinea': 'Equatorial Guinea',
    'Trinidad and Tobago': 'Trinidad and Tobago'
}


# Apply the country name standardization mapping to the emissions DataFrame
emissions['Country'] = emissions['Country'].replace(emissions_country_mapping)

emissions.reset_index(drop=True, inplace=True)

In [13]:
emissions['Date'] = pd.to_datetime(emissions['Date'])

emissions['Year'] = emissions['Date'].dt.year

emissions = emissions.drop(columns=['Date'])

emissions = emissions[['Country', 'Year', 'Kilotons of Co2', 'Metric Tons Per Capita']]

In [23]:
emissions['Country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Democratic Republic of the Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Swaziland', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyz Republic',
       'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria',
       "Democratic People's Republic Of Korea", 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Republic of the Congo', 'Romania', 'Russia',
       'Rwanda', 'Samoa', 'São Tomé and Príncipe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovak Republic', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'Republic Of Korea', 'South Sudan', 'Spain',
       'Sri Lanka', 'St. Kitts And Nevis', 'St. Lucia',
       'St. Vincent And The Grenadines', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania',
       'Thailand', 'East Timor', 'Togo', 'Tonga', 'Trinidad And Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'UAE', 'Uganda',
       'Ukraine', 'United Kingdom', 'United States', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

## Cleaning 'disasters'

In [25]:
disasters = disasters[(disasters['Disaster Subgroup'] != 'Extra-terrestrial') & 
                     (disasters['Disaster Subgroup'] != 'Biological')]

In [27]:
disasters = disasters[['Year', 'Disaster Type', 'Country', 'Continent']]

In [49]:
country_mapping = {
'United Kingdom of Great Britain and Northern Ireland (the)': 'United Kingdom',
    'Gambia (the)': 'Gambia',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Czechoslovakia': 'Czechia',
    'Iran (Islamic Republic of)': 'Iran',
    'Korea (the Republic of)': 'South Korea',
    'Myanmar': 'Myanmar',
    'Philippines (the)': 'Philippines',
    'United States of America (the)': 'United States',
    'Lao People\'s Democratic Republic (the)': 'Laos',
    'Taiwan (Province of China)': 'Taiwan',
    'Viet Nam': 'Vietnam',
    'Côte d’Ivoire': 'Ivory Coast',
    'Dominican Republic (the)': 'Dominican Republic',
    'Côte d\'Ivoire': 'Ivory Coast',
    'Cabo Verde': 'Cape Verde',
    'Guinea-Bissau': 'Guinea-Bissau',
    'Micronesia (Federated States of)': 'Micronesia',
    'Bahamas (the)': 'Bahamas',
    'Saint Lucia': 'Saint Lucia',
    'Saint Kitts and Nevis': 'St. Kitts and Nevis',
    'South Korea': 'Republic of Korea',
    'Congo (the Democratic Republic of the)': 'Democratic Republic of the Congo',
    'Congo (the)': 'Republic of the Congo',
    'Swaziland': 'Eswatini',
    'Yemen P Dem Rep': 'Yemen',
    'Yemen Arab Rep': 'Yemen',
    'Germany Fed Rep': 'Germany',
    'Germany Dem Rep': 'Germany',
    'Soviet Union': 'Soviet Union',  # Retained for historical purposes
    'Syrian Arab Republic': 'Syria',
    'Tanzania, United Republic of': 'Tanzania',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Serbia Montenegro': 'Serbia',
    'Russian Federation (the)': 'Russia',
    'Macedonia (the former Yugoslav Republic of)': 'North Macedonia',
    'Macao': 'Macau',
    'Virgin Island (U.S.)': 'U.S. Virgin Islands',
    'Yugoslavia': 'Yugoslavia',  # Historically significant
    'Uzbekistan': 'Uzbekistan',
    'Armenia': 'Armenia',
    'Brunei Darussalam': 'Brunei',
    'Moldova (the Republic of)': 'Moldova',
    'French Guiana': 'French Guiana',
    'Kazakhstan': 'Kazakhstan',
    'Palestine, State of': 'Palestine',
    'Saint Martin (French Part)': 'Saint Martin',
    'Saint Barthélemy': 'Saint Barthélemy',
    'Saint Helena, Ascension and Tristan da Cunha': 'Saint Helena, Ascension and Tristan da Cunha',
    'Timor-Leste': 'East Timor',
    'Northern Mariana Islands (the)': 'Northern Mariana Islands',
    'Isle of Man': 'Isle of Man',
    'Palau': 'Palau',
    'United Arab Emirates (the)': 'UAE',
    'Qatar': 'Qatar',
    'Sint Maarten (Dutch part)': 'Sint Maarten',
    'RÉunion': 'Reunion',
    'Anguilla': 'Anguilla',
    'Azores Islands': 'Azores',
    'Guadeloupe': 'Guadeloupe',
    'Hong Kong': 'Hong Kong',
    'Guam': 'Guam',
    'Martinique': 'Martinique',
    'Puerto Rico': 'Puerto Rico',
    'New Caledonia': 'New Caledonia',
    'Netherlands (the)': 'Netherlands',
    'Solomon Islands': 'Solomon Islands',
    'Kiribati': 'Kiribati',
    'New Zealand': 'New Zealand',
    'Mongolia': 'Mongolia',
    'Luxembourg': 'Luxembourg',
    'French Polynesia': 'French Polynesia',
    'Jamaica': 'Jamaica',
    'Iceland': 'Iceland',
    'Qatar': 'Qatar',
    'Seychelles': 'Seychelles',
    'Slovakia': 'Slovakia',
    'Slovenia': 'Slovenia',
    'Latvia': 'Latvia',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Canary Is': 'Canary Islands',
    'Cayman Islands (the)': 'Cayman Islands',
    'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Togo': 'Togo',
    'Tokelau': 'Tokelau',
    'Wallis and Futuna': 'Wallis and Futuna',
    'Netherlands Antilles': 'Netherlands Antilles',
    'American Samoa': 'American Samoa',
    'Burundi': 'Burundi',
    'Germany': 'Germany',
    'Belarus': 'Belarus',
    'Montserrat': 'Montserrat',
    'Finland': 'Finland',
    'Niue': 'Niue',
    'Norway': 'Norway',
    'Georgia': 'Georgia',
    'Iraq': 'Iraq',
    'Marshall Islands (the)': 'Marshall Islands',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Lithuania': 'Lithuania',
    'Russian Federation (the)': 'Russia',
    'Eritrea': 'Eritrea',
    'Kazakhstan': 'Kazakhstan',
    'Macao': 'Macau',
    'Virgin Island (U.S.)': 'U.S. Virgin Islands',
    'Tajikistan': 'Tajikistan',
    'Yemen': 'Yemen',
    'Uzbekistan': 'Uzbekistan',
    'Ukraine': 'Ukraine',
    'Turkmenistan': 'Turkmenistan',
    'Bhutan': 'Bhutan',
    'Azerbaijan': 'Azerbaijan',
    'Armenia': 'Armenia',
    'Brunei Darussalam': 'Brunei',
    'Moldova (the Republic of)': 'Moldova',
    'Libya': 'Libya',
    'Czech Republic (the)': 'Czechia',
    'Croatia': 'Croatia',
    'Kuwait': 'Kuwait',
    'Slovakia': 'Slovakia',
    'Seychelles': 'Seychelles',
    'Slovenia': 'Slovenia',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Latvia': 'Latvia',
    'Canary Is': 'Canary Islands',
    'Cayman Islands (the)': 'Cayman Islands',
    'Saint Helena, Ascension and Tristan da Cunha': 'Saint Helena, Ascension and Tristan da Cunha',
    'Timor-Leste': 'East Timor',
    'Northern Mariana Islands (the)': 'Northern Mariana Islands',
    'Estonia': 'Estonia',
    'Suriname': 'Suriname',
    'Palestine, State of': 'Palestine',
    'Montenegro': 'Montenegro',
    'Serbia': 'Serbia',
    'South Sudan': 'South Sudan',
    'Palau': 'Palau',
    'United Arab Emirates (the)': 'UAE',
    'Qatar': 'Qatar',
    'Saint Barthélemy': 'Saint Barthélemy',
    'Saint Martin (French Part)': 'Saint Martin',
    'Sint Maarten (Dutch part)': 'Sint Maarten',
    'Isle of Man': 'Isle of Man'
}

# Apply the country name standardization mapping
disasters['Country'] = disasters['Country'].replace(country_mapping)

In [51]:
disasters.reset_index(drop=True, inplace=True)

In [53]:
disasters = disasters[['Country', 'Continent', 'Year', 'Disaster Type']]

In [55]:
disasters['Country'].unique()

array(['Argentina', 'Australia', 'Benin', 'Bangladesh', 'Brazil',
       'Barbados', 'Botswana', 'Canada', 'Switzerland', 'China',
       'Colombia', 'Costa Rica', 'Cuba', 'Dominica', 'Ecuador', 'France',
       'Guadeloupe', 'Hong Kong', 'Hungary', 'Indonesia', 'India',
       'Chile', 'Afghanistan', 'Belgium', 'Cameroon', 'Spain', 'Ghana',
       'Guyana', 'Honduras', 'Germany', 'Fiji', 'United Kingdom', 'Haiti',
       'Ethiopia', 'Central African Republic', 'Algeria', 'Gambia',
       'Guatemala', 'Belize', 'Bolivia', 'Czechia', 'Austria', 'Egypt',
       'Grenada', 'Burkina Faso', 'Denmark', 'Guam', 'Bulgaria',
       'Comoros (the)', 'Djibouti', 'Greece', 'Peru', 'Papua New Guinea',
       'Iran', 'Israel', 'Italy', 'Republic of Korea', 'Morocco',
       'Madagascar', 'Mexico', 'Myanmar', 'Martinique', 'Malaysia',
       'Nepal', 'Panama', 'Philippines', 'Puerto Rico', 'Romania',
       'Turkey', 'United States', 'Japan', 'Kenya', 'Laos', 'Mozambique',
       'Nicaragua', 'Paraguay', 'Solomon Islands', 'Togo', 'Kiribati',
       'Mauritius', 'New Caledonia', 'Netherlands', 'Pakistan', 'Tuvalu',
       'Somalia', 'Iceland', 'Jamaica', 'Portugal', 'Tonga', 'Tunisia',
       'Sri Lanka', 'Niger (the)', 'Rwanda', 'Soviet Union', 'Syria',
       'Trinidad and Tobago', 'Tanzania', 'Sudan (the)', 'Sierra Leone',
       'Thailand', 'Mali', 'Mauritania', 'New Zealand', 'Senegal',
       'Sweden', 'Oman', 'Poland', 'RÃ©union', 'Chad', 'Taiwan',
       'Nigeria', 'Vietnam', 'Saint Vincent and the Grenadines',
       'Vanuatu', 'Yemen', 'South Africa', 'Zimbabwe',
       'Democratic Republic of the Congo', 'Zambia', 'Anguilla',
       'Albania', 'Dominican Republic', 'CÃ´te dâ\x80\x99Ivoire',
       'Azores', 'Cape Verde', 'Guinea', 'Guinea-Bissau', 'Angola',
       'Cook Islands (the)', 'Republic of the Congo',
       'Antigua and Barbuda', 'Cyprus', 'Bermuda', 'Micronesia',
       'Bahamas', 'Gabon', 'Malawi', 'Liberia', 'Saint Lucia', 'Namibia',
       'Mongolia', 'Saudi Arabia', 'Lesotho', 'Ireland', 'Lebanon',
       'Luxembourg', 'French Polynesia', 'St. Kitts and Nevis', 'Jordan',
       'Cambodia', 'Maldives',
       "Korea (the Democratic People's Republic of)", 'Yugoslavia',
       'Uganda', 'Venezuela (Bolivarian Republic of)', 'Eswatini',
       'El Salvador', 'Sao Tome and Principe', 'Samoa',
       'Turks and Caicos Islands (the)', 'Uruguay', 'Wallis and Futuna',
       'Tokelau', 'Netherlands Antilles', 'American Samoa', 'Burundi',
       'Belarus', 'Montserrat', 'Finland', 'Niue', 'Norway', 'Georgia',
       'Iraq', 'Marshall Islands', 'Kyrgyzstan', 'Lithuania', 'Russia',
       'Eritrea', 'North Macedonia', 'Kazakhstan', 'Macau',
       'U.S. Virgin Islands', 'Tajikistan', 'Uzbekistan', 'Serbia',
       'Ukraine', 'Turkmenistan', 'Bhutan', 'Azerbaijan', 'Armenia',
       'Brunei', 'Moldova', 'Libya', 'French Guiana', 'Croatia', 'Kuwait',
       'Virgin Island (British)', 'Slovakia', 'Seychelles', 'Slovenia',
       'Bosnia and Herzegovina', 'Latvia', 'Canary Islands',
       'Cayman Islands', 'Saint Helena, Ascension and Tristan da Cunha',
       'East Timor', 'Northern Mariana Islands', 'Estonia', 'Suriname',
       'Palestine', 'Montenegro', 'South Sudan', 'Palau', 'UAE', 'Qatar',
       'Saint BarthÃ©lemy', 'Saint Martin', 'Sint Maarten', 'Isle of Man'],
      dtype=object)

## Cleaning 'global energy consumption'

In [116]:
#gobal_energy = gobal_energy.drop([30, 31])
gobal_energy = gobal_energy.fillna('0')

In [118]:
gobal_energy

,Year,Energy Related CO2missions (Gigatonnes),Oil Production (Million barrels per day),Natural Gas Production (Billion Cubic Metres),Coal Production (million tons),Electricity Generation (Terawatt-hours),Hydroelectricity consumption in TWh,Nuclear energy consumption in TWh,Installed Solar Capacity (GW),Installed Wind Capacity in GW
0,1991,20.6,65.44,2026.8,4481.0,"12,218",2247.96,2089.56,0,1.93
1,1992,20.5,65.71,2039.4,4432.0,"12,330",2240.48,2105.4,0,2.17
2,1993,20.6,65.99,2073.5,4327.0,"12,592",2364.56,2179.32,0,2.5
3,1994,20.7,66.89,2095.7,4402.0,"12,917",2382.16,2217.6,0,2.99
4,1995,21.3,67.85,2136.1,4557.0,"13,375",2508.44,2314.84,0,3.49
5,1996,21.7,69.67,2230.0,4622.0,"13,789",2548.92,2397.12,0,6.1
6,1997,22.1,71.85,2233.0,4621.0,"14,121",2589.4,2381.28,0,7.6
7,1998,22.3,73.28,2284.1,4569.0,"14,503",2620.64,2422.2,0,10.2
8,1999,22.4,71.83,2339.3,4499.0,"14,918",2640.0,2514.16,0,13.6
9,2000,23.1,74.48,2421.8,4638.0,"15,556",2714.36,2574.0,1.3,17.0
10,2001,23.5,74.49,2477.2,4860.0,"15,789",2615.8,2645.28,1.6,24.0
11,2002,23.8,74.95,2518.9,4914.0,"16,345",2633.84,2686.2,2.1,31.0
12,2003,24.9,77.57,2616.6,5263.0,"16,924",2632.96,2632.52,2.6,39.0
13,2004,26.0,80.97,2688.5,5663.0,"17,727",2797.52,2749.56,3.7,48.0
14,2005,27.0,82.01,2770.4,6022.0,"18,454",2914.12,2757.48,5.1,59.0
15,2006,27.8,82.48,2869.4,6367.0,"19,155",3023.68,2794.88,6.7,74.0
16,2007,28.9,82.29,2939.3,6644.0,"20,046",3081.76,2735.92,9.2,94.0
17,2008,29.1,82.93,3047.2,6842.0,"20,422",3201.88,2723.6,16.0,121.0
18,2009,28.7,81.26,2955.9,6968.0,"20,265",3245.0,2702.04,23.0,159.0
19,2010,30.4,83.29,3150.8,7354.0,21570.7,3427.16,2755.72,40.0,198.0
20,2011,31.3,84.04,3258.0,7833.0,22257,3482.6,2636.92,70.0,238.0
21,2012,31.6,86.26,3326.8,7936.0,22806.3,3655.08,2461.8,101.0,283.0
22,2013,32.2,86.67,3366.1,7976.0,23435.2,3781.36,2480.72,138.0,319.0
23,2014,32.3,88.83,3437.9,7939.0,24031.7,3870.68,2530.0,178.0,370.0
24,2015,32.2,91.63,3511.7,7669.0,24270.5,3874.2,2564.32,230.0,433.0
25,2016,32.2,91.99,3552.1,7293.0,24915.2,4018.52,2601.28,308.0,488.0
26,2017,32.7,92.57,3676.2,7545.0,25623.9,4041.84,2624.16,407.0,540.0
27,2018,33.5,94.85,3852.9,7827.0,26659.1,4231.0,2700.46,508.0,592.0
28,2019,33.4,94.96,3976.2,7960.0,27001,4294.0,2796.35,629.0,651.0
29,2020,31.5,88.39,3853.7,7575.0,26889,4370.0,2693.98,773.2,744.0
30,2021,33.0,89.9,0,0,28466,4250.0,2800.27,939.0,837.0
31,2022,0,0,0,0,0,0,0,0,0

## Cleaning 'global temperatures'

In [8]:
global_temps.dropna(how = 'all', inplace = True)

In [16]:
global_temps = global_temps[global_temps['Troposphere'] == 'Lower']

In [26]:
global_temps = global_temps[['ï»¿Year', 'Mo', 'Globe', 'Land', 'Ocean']]

In [34]:
global_temps = global_temps.rename(columns={
    'ï»¿Year': 'Year',
    'Mo': 'Month'
})

In [44]:
global_temps

     Year  Month  Globe  Land  Ocean
0    1978   12.0  -0.48 -0.51  -0.47
1    1979    1.0  -0.47 -0.64  -0.41
2    1979    2.0  -0.43 -0.56  -0.39
3    1979    3.0  -0.38 -0.51  -0.33
4    1979    4.0  -0.40 -0.57  -0.34
..    ...    ...    ...   ...    ...
519  2022    3.0   0.15  0.28   0.10
520  2022    4.0   0.26  0.37   0.22
521  2022    5.0   0.17  0.30   0.12
522  2022    6.0   0.06  0.32  -0.04
523  2022    7.0   0.36  0.52   0.29

[524 rows x 5 columns]

## Export to CSV

In [42]:
temperature.to_csv("Created CSV's/temperature.csv", index=False)
disasters.to_csv("Created CSV's/disasters.csv", index=False)
emissions.to_csv("Created CSV's/emissions.csv", index=False)
global_temps.to_csv("Created CSV's/global_temps.csv", index=False)